services:
  app:
    image: lesson-04:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      -   redis
    environment:
      - APP_MESSAGE="Welcome to the Course App"
      - APP_STORE=redis
      - APP_REDIS_URL=redis://:password@redis:6379/0

  redis:
    image: redis:alpine
    command: "redis-server --requirepass password"
    restart: unless-stopped
