services:
  pythonapp:
    build:
      context: ../../../../
      dockerfile: homeworks/dudnyk/module-2/lesson-4/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - APP_STORE=redis
      - APP_REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:8.0
    ports:
      - "6379:6379"