apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: course-app.207.127.90.43.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-app
            port:
              number: 80
