apiVersion: v1
kind: ConfigMap
metadata:
  name: course-app-config
  namespace: dtimchuk-dev
  labels:
    app: course-app
    env: development
data:
  APP_NAME: "Course Application"
  APP_VERSION: "1.0"
  APP_ENVIRONMENT: "development"
  LOG_LEVEL: "info"
  MESSAGE: "Hello from ConfigMap version 1"