services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: course_app
    ports:
      - "8080:8080"
    environment:
      APP_MESSAGE: "Welcome to Course App from Docker"
      APP_STORE: "redis"
      APP_REDIS_URL: "redis://redis:6379/0"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: course_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "20", "1"]
    volumes:
      - redis_data:/data

volumes:
  redis_data: