services:
  web:
    build: 
      context: ../../../../apps/course-app
      dockerfile: ../../homeworks/sokhatskyi/module-02/lesson-05/Dockerfile
    ports:
      - "8080:8080"
    environment:
        APP_STORE: redis
        APP_REDIS_URL: redis://redis:6379/0
    depends_on:
        redis:
            condition: service_healthy
  redis:
    image: "redis:8.2.3"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    volumes:
      - appdata:/data
volumes:
  appdata: