services:
  pythonapp:
    image: course-app:v1.0 
    ports:
      - "8080:8080"
    environment:
      - APP_STORE=redis
      - APP_REDIS_URL=redis://redis:6379/0 
    depends_on:
       redis:
           condition: service_healthy 
    healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
  redis:
    image: redis:8.0

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 3s

    volumes:
      - appdata:/data
volumes:
  appdata:
