apiVersion: v1
kind: Service
metadata:
  name: course-app-nodeport
spec:
  type: NodePort
  selector:
    app: course-app
  ports:
  - name: http
    port: 8080         # сервіс-порт
    targetPort: 8080   # контейнер-порт
    nodePort: 30080    # вибраний NodePort (30000-32767). Можна змінити.
