apiVersion: v1
kind: ConfigMap
metadata:
  name: course-app-config
data:
  APP_STORE: "redis"
  APP_REDIS_URL: "redis://redis:6379/0"
  pupupu.sh: |
    #!/bin/sh
    echo "Hi container"
  API_VERSION: "v3"