version: '3.9'

services:
  course-app:
    build: ../../../../apps/course-app
    container_name: course-app
    ports:
      - "8080:8080"
    environment:
      - APP_MESSAGE=Hello, Docker Compose!
      - APP_STORE=redis
      - APP_REDIS_URL=redis://redis:6379/0
#      - APP_DB_PATH=/app/data/db.sqlite3
    depends_on:
      - redis
    networks:
      - backend
#    volumes:
#      - ./data:/app/data

  redis:
    image: redis:7-alpine
    container_name: course-redis
    networks:
      - backend
#    ports:
#      - "6379:6379"

networks:
  backend:
    driver: bridge
